small improvements

diff --git a/.github/workflows/mender-artifact.yml b/.github/workflows/mender-artifact.yml
--- a/.github/workflows/mender-artifact.yml
+++ b/.github/workflows/mender-artifact.yml
@@ -46,30 +46,30 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: artifact
-      - name: Get Auth Credentials
+      - name: Get Auth Token
         env:
           MENDER_SERVER_URL: https://hosted.mender.ioMENDE
         run: |
           if [ ! -z secrets.MENDER_SERVER_ACCESS_TOKEN ]; then
-            TOKEN=${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
+            MENDER_SERVER_ACCESS_TOKEN=${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
           elif [[ ! -z ${{ secrets.MENDER_SERVER_USER }} && ! -z ${{ secrets.MENDER_SERVER_PASSWORD }} ]]; then
-            TOKEN=$(curl -s -X POST -u ${{ secrets.MENDER_SERVER_USER }}:${{ secrets.MENDER_SERVER_PASSWORD }} ${MENDER_SERVER_URL}/api/management/v1/useradm/auth/login)
+            MENDER_SERVER_ACCESS_TOKEN=$(curl -s -X POST -u ${{ secrets.MENDER_SERVER_USER }}:${{ secrets.MENDER_SERVER_PASSWORD }} ${MENDER_SERVER_URL}/api/management/v1/useradm/auth/login)
           else
             echo "ERROR: Auth credentials are not provided"
             exit 1
           fi
-          echo "TOKEN=${TOKEN}" >> ${GITHUB_ENV}
+          echo "MENDER_SERVER_ACCESS_TOKEN=${MENDER_SERVER_ACCESS_TOKEN}" >> ${GITHUB_ENV}
       - name: Upload Artifact to Mender Server
         env:
           MENDER_ARTIFACT_NAME: artifact.mender
           MENDER_SERVER_URL: https://hosted.mender.io
         run: |
           artifact_name=$(mender-artifact read --no-progress ${MENDER_ARTIFACT_NAME} | grep "Name:" | awk {'print $2'})
-          if [ $(mender-cli artifacts list --server ${MENDER_SERVER_URL} --token-value ${TOKEN} | grep -c ${artifact_name}) -gt 0 ]; then
+          if [ $(mender-cli artifacts list --server ${MENDER_SERVER_URL} --token-value ${MENDER_SERVER_ACCESS_TOKEN} | grep -c ${artifact_name}) -gt 0 ]; then
             echo "WARN: artifact ${MENDER_SERVER_URL} with name ${artifact_name} already exists on the server, upload is skipped"
             exit 0
           fi
-          mender-cli artifacts upload --no-progress --server ${MENDER_SERVER_URL} --token-value ${TOKEN} ${MENDER_ARTIFACT_NAME}
+          mender-cli artifacts upload --no-progress --server ${MENDER_SERVER_URL} --token-value ${MENDER_SERVER_ACCESS_TOKEN} ${MENDER_ARTIFACT_NAME}
 
 
   deploy:
@@ -93,23 +93,29 @@ jobs:
           CI_COMMIT_SHORT_SHA="${GITHUB_SHA:0:8}"
           DEPLOYMENT_NAME=${ARTIFACT_NAME}_${CI_COMMIT_SHORT_SHA}
           echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" | tee -a ${GITHUB_ENV}
+      - name: Get Auth Token
+        env:
+          MENDER_SERVER_URL: https://hosted.mender.ioMENDE
+        run: |
+          if [ ! -z secrets.MENDER_SERVER_ACCESS_TOKEN ]; then
+            MENDER_SERVER_ACCESS_TOKEN=${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}
+          elif [[ ! -z ${{ secrets.MENDER_SERVER_USER }} && ! -z ${{ secrets.MENDER_SERVER_PASSWORD }} ]]; then
+            MENDER_SERVER_ACCESS_TOKEN=$(curl -s -X POST -u ${{ secrets.MENDER_SERVER_USER }}:${{ secrets.MENDER_SERVER_PASSWORD }} ${MENDER_SERVER_URL}/api/management/v1/useradm/auth/login)
+          else
+            echo "ERROR: Auth credentials are not provided"
+            exit 1
+          fi
+          echo "MENDER_SERVER_ACCESS_TOKEN=${MENDER_SERVER_ACCESS_TOKEN}" >> ${GITHUB_ENV}
       - name: Get Group's Devices List
         env:
           MENDER_DEPLOYMENT_NAME: grp-1
           MENDER_SERVER_URL: https://hosted.mender.io
         run: |
-          MENDER_DEVICES_LIST=$(curl -s -H "Authorization: Bearer ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}" ${MENDER_SERVER_URL}/api/management/v1/inventory/groups/${MENDER_DEPLOYMENT_NAME}/devices)
+          MENDER_DEVICES_LIST=$(curl -s -H "Authorization: Bearer ${MENDER_SERVER_ACCESS_TOKEN}" ${MENDER_SERVER_URL}/api/management/v1/inventory/groups/${MENDER_DEPLOYMENT_NAME}/devices)
           echo "MENDER_DEVICES_LIST=$MENDER_DEVICES_LIST" | tee -a ${GITHUB_ENV}
       - name: Create Deployment
         env:
           MENDER_SERVER_URL: https://hosted.mender.io
         run: |
-          [ -z "${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}" ] && echo MENDER_SERVER_ACCESS_TOKEN is empty
-          # STATUS_CODE=$(
-            curl -X POST ${MENDER_SERVER_URL}/api/management/v1/deployments/deployments \
-            -H "Content-Type: application/json" \
-            -H "Accept: application/json" \
-            -H "Authorization: Bearer ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}" \
-            --data-raw "{\"name\": \"${DEPLOYMENT_NAME}\", \"artifact_name\": \"${ARTIFACT_NAME}\", \"devices\": ${MENDER_DEVICES_LIST}}"
-            # )
-          # [ "${STATUS_CODE}" -eq 201 ] && echo "INFO: Deployment ${DEPLOYMENT_NAME} successfully created" || { echo "ERROR: Failed to create deployment (responce code ${STATUS_CODE})"; exit 1; }
+          STATUS_CODE=$(curl -s -w "%{http_code}" -X POST ${MENDER_SERVER_URL}/api/management/v1/deployments/deployments -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer ${{ secrets.MENDER_SERVER_ACCESS_TOKEN }}" --data-raw "{\"name\": \"${DEPLOYMENT_NAME}\", \"artifact_name\": \"${ARTIFACT_NAME}\", \"devices\": ${MENDER_DEVICES_LIST}}")
+          [ "${STATUS_CODE}" -eq 201 ] && echo "INFO: Deployment ${DEPLOYMENT_NAME} successfully created" || { echo "ERROR: Failed to create deployment (responce code ${STATUS_CODE})"; exit 1; }
